// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {backend} from '../models';
import {context} from '../models';

export function AddConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListConnections():Promise<Array<model.Connection>>;

export function Query(arg1:string,arg2:string):Promise<backend.QueryResult>;

export function Startup(arg1:context.Context):Promise<void>;
