// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTableInfo(arg1) {
  return window['go']['main']['App']['GetTableInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListDatabase() {
  return window['go']['main']['App']['ListDatabase']();
}

export function ListTableForDatabase(arg1) {
  return window['go']['main']['App']['ListTableForDatabase'](arg1);
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function Query(arg1, arg2) {
  return window['go']['main']['App']['Query'](arg1, arg2);
}

export function SetActiveConnection(arg1) {
  return window['go']['main']['App']['SetActiveConnection'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function TitleBarPressedDouble() {
  return window['go']['main']['App']['TitleBarPressedDouble']();
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}
